import type { GibTableDef } from "../../kdv/config/kdv1Tables";
import {
  BANKA_AKTIF,
  BANKA_GELIR,
  BANKA_NAZIM,
  BANKA_PASIF,
  FK_AKTIF,
  FK_GELIR,
  FK_PASIF,
  KATILIM_AKTIF,
  KATILIM_BDH,
  KATILIM_GELIR,
  KATILIM_PASIF,
  SIGORTA_AKTIF,
  SIGORTA_GELIR,
  SIGORTA_PASIF,
  TDHP_AKTIF,
  TDHP_GELIR,
  TDHP_PASIF,
  YF_AKTIF,
  YF_GELIR,
  YF_PASIF,
  ekBildirimGrid,
  idariForm,
  maliTablo,
} from "./maliTabloHelpers";

export const KURUMLAR_TABLE_DEFS: Record<string, GibTableDef> = {
  s1_1: idariForm("s1_1", "1.1 İdari Bilgiler", [
    { key: "donem_yil", label: "Hesap Dönemi Yılı", type: "number", width: 100 },
    { key: "ozel_hesap", label: "Özel Hesap Dönemi", type: "text" },
  ]),
  s1_2: {
    id: "s1_2",
    title: "1.2 Kurum Tipi / Kazanç Tespiti",
    kind: "form",
    fields: [
      {
        key: "kazanc_tespit",
        label: "Kazanç Tespit Yöntemi",
        type: "select",
        options: [
          { value: "bilanco", label: "Bilanço" },
          { value: "isletme", label: "İşletme Hesabı" },
        ],
      },
      {
        key: "bilanco_tipi",
        label: "Bilanço Tipi",
        type: "select",
        options: [
          { value: "tdhp", label: "Tek Düzen Hesap Planı" },
          { value: "banka", label: "Banka" },
          { value: "katilim", label: "Katılım Bankası" },
          { value: "sigorta", label: "Sigorta" },
          { value: "fk", label: "Finansal Kiralama" },
          { value: "yf", label: "Yatırım Fonları" },
        ],
      },
      {
        key: "finans_orani",
        label: "Finans Kurumu Artırımlı Oran",
        type: "select",
        options: [
          { value: "hayir", label: "Hayır (genel oran)" },
          { value: "evet", label: "Evet (%30)" },
        ],
      },
    ],
  },
  s1_3: {
    id: "s1_3",
    title: "1.3 Kuruma Bağlı İşyerleri",
    kind: "grid",
    defaultRows: 2,
    columns: [
      { key: "tur", label: "İşyeri Türü", type: "text", width: 140 },
      { key: "adet", label: "Adet", type: "number", width: 80 },
      { key: "adres", label: "Adres / İl", type: "text" },
    ],
  },
  s2_1: {
    id: "s2_1",
    title: "2.1 Ticari Bilanço Kârı",
    kind: "summary",
    fields: [
      { key: "ticari_kar", label: "Ticari Bilanço Kârı / Zararı", type: "number" },
      { key: "duzeltmeler", label: "Düzeltmeler (+/-)", type: "number" },
    ],
  },
  s2_2: ekBildirimGrid("s2_2", "2.2 Kanunen Kabul Edilmeyen Giderler"),
  s2_3: {
    id: "s2_3",
    title: "2.3 İstisnalar (KVK 5/1)",
    description: "Kurumlar Vergisi Kanunu 5/1 bentleri.",
    kind: "grid",
    defaultRows: 3,
    columns: [
      {
        key: "bent",
        label: "Bent",
        type: "select",
        options: [
          { value: "a", label: "5/1-a İştirak kazançları" },
          { value: "b", label: "5/1-b Yurtdışı iştirak" },
          { value: "c", label: "5/1-c Emisyon primi" },
          { value: "e", label: "5/1-e Taşınmaz / iştirak satış" },
          { value: "f", label: "5/1-f Risturnlar" },
          { value: "i", label: "5/1-i Diğer" },
        ],
        width: 200,
      },
      { key: "aciklama", label: "Açıklama", type: "text" },
      { key: "tutar", label: "İstisna Tutarı", type: "number", width: 120 },
      { key: "hesap", label: "Hesap", type: "account", width: 140 },
    ],
  },
  s2_4: ekBildirimGrid("s2_4", "2.4 İndirimler"),
  s2_5: ekBildirimGrid("s2_5", "2.5 Geçmiş Yıl Zararları"),
  s2_6: {
    id: "s2_6",
    title: "2.6 Kurumlar Vergisi Matrahı",
    kind: "summary",
    fields: [
      { key: "matrah", label: "Kurumlar Vergisi Matrahı", type: "number" },
      { key: "zarar", label: "Zarar Varsa", type: "number" },
    ],
  },
  s3_1: {
    id: "s3_1",
    title: "3.1 Hesaplanan Kurumlar Vergisi",
    kind: "summary",
    fields: [
      { key: "oran", label: "Oran (%)", type: "number" },
      { key: "hesaplanan", label: "Hesaplanan KV", type: "number" },
    ],
  },
  s3_2: ekBildirimGrid("s3_2", "3.2 İndirimli Oran / Teşvik"),
  s3_3: ekBildirimGrid("s3_3", "3.3 Mahsuplar / Geçici Vergi"),
  s3_4: {
    id: "s3_4",
    title: "3.4 Ödenecek / İade",
    kind: "summary",
    fields: [
      { key: "odenecek", label: "Ödenecek Kurumlar Vergisi", type: "number" },
      { key: "iade", label: "İade / Terkin", type: "number" },
    ],
  },
  bil_td_aktif: maliTablo("bil_td_aktif", "Tek Düzen — Aktif", "Ayrıntılı bilanço aktif.", TDHP_AKTIF),
  bil_td_pasif: maliTablo("bil_td_pasif", "Tek Düzen — Pasif", "Ayrıntılı bilanço pasif.", TDHP_PASIF),
  bil_td_gt: maliTablo("bil_td_gt", "Tek Düzen — Gelir Tablosu", "Ayrıntılı gelir tablosu.", TDHP_GELIR),
  bil_bk_aktif: maliTablo("bil_bk_aktif", "Banka — Aktif", "Banka aktif.", BANKA_AKTIF),
  bil_bk_pasif: maliTablo("bil_bk_pasif", "Banka — Pasif", "Banka pasif.", BANKA_PASIF),
  bil_bk_nazim: maliTablo("bil_bk_nazim", "Banka — Nazım", "Nazım hesaplar.", BANKA_NAZIM),
  bil_bk_gt: maliTablo("bil_bk_gt", "Banka — Solo Gelir Tablosu", "Banka GT.", BANKA_GELIR),
  bil_kt_aktif: maliTablo("bil_kt_aktif", "Katılım — Aktif", "Katılım aktif.", KATILIM_AKTIF),
  bil_kt_pasif: maliTablo("bil_kt_pasif", "Katılım — Pasif", "Katılım pasif.", KATILIM_PASIF),
  bil_kt_bdh: maliTablo("bil_kt_bdh", "Katılım — Bilanço Dışı", "BDH.", KATILIM_BDH),
  bil_kt_gt: maliTablo("bil_kt_gt", "Katılım — Gelir Tablosu", "Katılım GT.", KATILIM_GELIR),
  bil_sg_aktif: maliTablo("bil_sg_aktif", "Sigorta — Aktif", "Sigorta aktif.", SIGORTA_AKTIF),
  bil_sg_pasif: maliTablo("bil_sg_pasif", "Sigorta — Pasif", "Sigorta pasif.", SIGORTA_PASIF),
  bil_sg_gt: maliTablo("bil_sg_gt", "Sigorta — Solo Gelir Tablosu", "Sigorta GT.", SIGORTA_GELIR),
  bil_sg_dipnot: {
    id: "bil_sg_dipnot",
    title: "Sigorta — Dipnot",
    kind: "form",
    fields: [{ key: "dipnot", label: "Denetçi / Açıklama Notları", type: "text" }],
  },
  bil_fk_aktif: maliTablo("bil_fk_aktif", "Finansal Kiralama — Aktif", "FK aktif.", FK_AKTIF),
  bil_fk_pasif: maliTablo("bil_fk_pasif", "Finansal Kiralama — Pasif", "FK pasif.", FK_PASIF),
  bil_fk_gt: maliTablo("bil_fk_gt", "Finansal Kiralama — Gelir Tablosu", "FK GT.", FK_GELIR),
  bil_yf_aktif: maliTablo("bil_yf_aktif", "Yatırım Fonları — Aktif", "YF aktif.", YF_AKTIF),
  bil_yf_pasif: maliTablo("bil_yf_pasif", "Yatırım Fonları — Pasif", "YF pasif.", YF_PASIF),
  bil_yf_gt: maliTablo("bil_yf_gt", "Yatırım Fonları — Gelir Tablosu", "YF GT.", YF_GELIR),
  s5_1: ekBildirimGrid("s5_1", "5.1 Transfer Fiyatlandırması"),
  s5_2: {
    id: "s5_2",
    title: "5.2 Gerçek Faydalanıcı Bildirimi",
    kind: "grid",
    defaultRows: 2,
    columns: [
      { key: "ad_soyad", label: "Ad Soyad / Unvan", type: "text", width: 160 },
      { key: "tckn_vkn", label: "TCKN / VKN", type: "text", width: 120 },
      { key: "uyruk", label: "Uyruk", type: "text", width: 80 },
      { key: "pay", label: "Pay Oranı (%)", type: "number", width: 100 },
      { key: "aciklama", label: "Açıklama", type: "text" },
    ],
  },
  s5_3: ekBildirimGrid("s5_3", "5.3 AR-GE İndirimi"),
  s5_4: {
    id: "s5_4",
    title: "5.4 Kâr Dağıtım Tablosu",
    kind: "summary",
    fields: [
      { key: "dagitilabilir", label: "Dağıtılabilir Kâr", type: "number" },
      { key: "yedek", label: "Yedeklere Ayrılan", type: "number" },
      { key: "temettu", label: "Temettü", type: "number" },
    ],
  },
  s5_5: ekBildirimGrid("s5_5", "5.5 İndirimli Kurumlar Vergisi"),
  s5_6: ekBildirimGrid("s5_6", "5.6 Kontrol Edilen Yabancı Kurum"),
  s5_7: ekBildirimGrid("s5_7", "5.7 Örtülü Sermaye"),
  s6_1: {
    id: "s6_1",
    title: "6.1 SM / SMMM Bilgileri",
    kind: "form",
    fields: [
      { key: "adi", label: "Adı Soyadı", type: "text" },
      {
        key: "sifat",
        label: "Sıfat",
        type: "select",
        options: [
          { value: "sm", label: "SM" },
          { value: "smmm", label: "SMMM" },
          { value: "ymm", label: "YMM" },
        ],
      },
      { key: "oda_no", label: "Oda Sicil No", type: "text" },
      { key: "tckn", label: "TCKN", type: "text" },
      { key: "tarih", label: "Tarih", type: "text" },
    ],
  },
};
