import type { RightMenuItem } from "@/components/ui";

/** Kurumlar Vergisi (yıllık) — sağ dikey iç menü */
export const KURUMLAR_MENU_ITEMS: RightMenuItem[] = [
  { id: "prepare", label: "Hazırlama" },

  { id: "g_genel", label: "1. Genel Bilgiler", isGroup: true },
  { id: "s1_1", label: "1.1 İdari Bilgiler", level: 1 },
  { id: "s1_2", label: "1.2 Kurum Tipi / Kazanç Tespiti", level: 1 },
  { id: "s1_3", label: "1.3 Kuruma Bağlı İşyerleri", level: 1 },

  { id: "g_matrah", label: "2. Matrah Bildirimi", isGroup: true },
  { id: "s2_1", label: "2.1 Ticari Bilanço Kârı", level: 1 },
  { id: "s2_2", label: "2.2 Kanunen Kabul Edilmeyen Giderler", level: 1 },
  { id: "s2_3", label: "2.3 İstisnalar (KVK 5/1)", level: 1 },
  { id: "s2_4", label: "2.4 İndirimler", level: 1 },
  { id: "s2_5", label: "2.5 Geçmiş Yıl Zararları", level: 1 },
  { id: "s2_6", label: "2.6 Kurumlar Vergisi Matrahı", level: 1 },

  { id: "g_vergi", label: "3. Vergi Bildirimi", isGroup: true },
  { id: "s3_1", label: "3.1 Hesaplanan Kurumlar Vergisi", level: 1 },
  { id: "s3_2", label: "3.2 İndirimli Oran / Teşvik", level: 1 },
  { id: "s3_3", label: "3.3 Mahsuplar / Geçici Vergi", level: 1 },
  { id: "s3_4", label: "3.4 Ödenecek / İade", level: 1 },

  { id: "g_bilanco", label: "4. Ayrıntılı Bilanço / Gelir Tablosu", isGroup: true },
  { id: "g_tdhp", label: "4.1 Tek Düzen Hesap Planı", isGroup: true, level: 1 },
  { id: "bil_td_aktif", label: "Aktif", level: 2 },
  { id: "bil_td_pasif", label: "Pasif", level: 2 },
  { id: "bil_td_gt", label: "Gelir Tablosu", level: 2 },
  { id: "g_banka", label: "4.2 Banka", isGroup: true, level: 1 },
  { id: "bil_bk_aktif", label: "Aktif", level: 2 },
  { id: "bil_bk_pasif", label: "Pasif", level: 2 },
  { id: "bil_bk_nazim", label: "Nazım Hesaplar", level: 2 },
  { id: "bil_bk_gt", label: "Solo Gelir Tablosu", level: 2 },
  { id: "g_katilim", label: "4.3 Katılım Bankası", isGroup: true, level: 1 },
  { id: "bil_kt_aktif", label: "Aktif", level: 2 },
  { id: "bil_kt_pasif", label: "Pasif", level: 2 },
  { id: "bil_kt_bdh", label: "Bilanço Dışı Hesaplar", level: 2 },
  { id: "bil_kt_gt", label: "Gelir Tablosu", level: 2 },
  { id: "g_sigorta", label: "4.4 Sigorta", isGroup: true, level: 1 },
  { id: "bil_sg_aktif", label: "Aktif", level: 2 },
  { id: "bil_sg_pasif", label: "Pasif", level: 2 },
  { id: "bil_sg_gt", label: "Solo Gelir Tablosu", level: 2 },
  { id: "bil_sg_dipnot", label: "Dipnot", level: 2 },
  { id: "g_fk", label: "4.5 Finansal Kiralama", isGroup: true, level: 1 },
  { id: "bil_fk_aktif", label: "Aktif", level: 2 },
  { id: "bil_fk_pasif", label: "Pasif", level: 2 },
  { id: "bil_fk_gt", label: "Gelir Tablosu", level: 2 },
  { id: "g_yf", label: "4.6 Yatırım Fonları", isGroup: true, level: 1 },
  { id: "bil_yf_aktif", label: "Aktif", level: 2 },
  { id: "bil_yf_pasif", label: "Pasif", level: 2 },
  { id: "bil_yf_gt", label: "Gelir Tablosu", level: 2 },

  { id: "g_ekler", label: "5. Ek Tablolar", isGroup: true },
  { id: "s5_1", label: "5.1 Transfer Fiyatlandırması", level: 1 },
  { id: "s5_2", label: "5.2 Gerçek Faydalanıcı Bildirimi", level: 1 },
  { id: "s5_3", label: "5.3 AR-GE İndirimi", level: 1 },
  { id: "s5_4", label: "5.4 Kâr Dağıtım Tablosu", level: 1 },
  { id: "s5_5", label: "5.5 İndirimli Kurumlar Vergisi", level: 1 },
  { id: "s5_6", label: "5.6 Kontrol Edilen Yabancı Kurum", level: 1 },
  { id: "s5_7", label: "5.7 Örtülü Sermaye", level: 1 },

  { id: "g_duzenleyen", label: "6. Düzenleyen", isGroup: true },
  { id: "s6_1", label: "6.1 SM / SMMM Bilgileri", level: 1 },

  { id: "accounts", label: "Hesap Bağlantıları" },
  { id: "list", label: "Oluşturulan Beyannameler" },
  { id: "outputs", label: "Çıktılar" },
];
